services:
  db:
    container_name: db_pokemon
    image: postgres:16.2
    volumes:
      - db-pokemon-data:/var/lib/postgresql/data
      - ./docs/sql/ddl/ddl.sql:/docker-entrypoint-initdb.d/a.sql
      - ./docs/sql/dml/dml.sql:/docker-entrypoint-initdb.d/b.sql
      - ./python/scripts_de_api/cidade.sql:/docker-entrypoint-initdb.d/c.sql
      - ./python/scripts_de_api/floresta.sql:/docker-entrypoint-initdb.d/d.sql
      - ./python/scripts_de_api/floresta2.sql:/docker-entrypoint-initdb.d/e.sql
      - ./python/scripts_de_api/floresta3.sql:/docker-entrypoint-initdb.d/f.sql
      - ./docs/sql/trigger_procedure/trigger.sql:/docker-entrypoint-initdb.d/g.sql

    environment:
      POSTGRES_USER: "pokemon"
      POSTGRES_PASSWORD: "123456"
      POSTGRES_DB: db_pokemon
      PGPORT: 5434
    ports:
      - 5434:5434 

volumes:
  db-pokemon-data:
