services:
  db:
    container_name: db_pokemon
    image: postgres:16.2
    volumes:
      - db-pokemon-data:/var/lib/postgresql/data
      - ./docs/script:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: "pokemon"
      POSTGRES_PASSWORD: "123456"
      POSTGRES_DB: db_pokemon
      PGPORT: 5434
    ports:
      - 5434:5434 
volumes:
  db-pokemon-data: