services:
  db:
    container_name: db_pokemon
    image: postgres:16.2
    volumes:
      - db-pokemon-data:/var/lib/postgresql/data
      - ./docs/script:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: db_pokemon
      PGPORT: 5434
    ports:
      - 5434:5434
    env_file:
      .env
volumes:
  db-pokemon-data: