site_name: Pokémon Mystery Dungeon

repo_name: 2024.1-Pokemon
repo_url: https://github.com/SBD1/2024.1-Pokemon

theme:
  logo: images/logo.png
  favicon: images/logo-pokebola.png
  language: pt-BR
  icon:
    repo: fontawesome/brands/github
  palette: 
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - content.code.copy

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      pygments_lang_class: true
      auto_title: true
      linenums: true
  - pymdownx.superfences
  - attr_list
  - md_in_html

plugins:
  - glightbox

extra_css:
  - stylesheets/extra.css
    
nav:
  - Início: index.md
  - Modelagem:
    - Dicionário de dados: modelagem/dicionario_dados.md
    - Modelo Entidade-Relacionamento: modelagem/modelo-entidade-relacionamento.md
    - Diagrama Entidade-Relacionamento: modelagem/diagrama-entidade-relacionamento.md
  - SQL:
    - DDL: sql/ddl/ddl.md
  - Apresentações:
    - Apresentação 1: entregas/modulo1/apresentacao_1.md
    - Apresentação 2: entregas/modulo2/apresentacao_2.md
    - Apresentação 3: entregas/modulo3/apresentacao_3.md
