repo_name: 2024.1-Pokemon
site_name: Pokemon
repo_url: https://github.com/SBD1/2024.1-Pokemon

theme:
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: red
      toggle:
        icon: material/weather-sunny
        name: Dark mode

  # Palette toggle for dark mode
    - scheme: slate
      primary: red
      toggle:
        icon: material/weather-night
        name: Light mode

  logo: docs/images/logo.png
  favicon: docs/images/logo-pokebola.png
  
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.footer

nav:
  - Início: index.md
