CREATE TABLE vendedor (
    id_pokemon INT,
    id_vendendor INT,
    nivel INT NOT NULL,
    vida INT NOT NULL,
    ataque_fisico INT NOT NULL,
    defesa_fisica INT NOT NULL,
    ataque_especial INT NOT NULL,
    velocidade INT NOT NULL,
    acuracia INT NOT NULL,
    evasao INT NOT NULL,
    status VARCHAR(255) NOT NULL,
    nome VARCHAR(255) NOT NULL,
    posicao INT, 
    item_1 INT,
    item_2 INT,
    item_3 INT,
    FOREIGN KEY (item_1) REFERENCES item(id_item),
    FOREIGN KEY (item_2) REFERENCES item(id_item),
    FOREIGN KEY (item_3) REFERENCES item(id_item),
    FOREIGN KEY (id_pokemon) REFERENCES pokemon(id_pokemon),
    FOREIGN KEY (id_vendendor) REFERENCES npc(id_npc),
    FOREIGN KEY (posicao) REFERENCES terreno(id_terreno)
);
